/** 与后端 server/pkg/rbac/rbac.go 保持一致 */
export const PERM = {
  USER_READ: 'user:read',
  USER_CREATE: 'user:create',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  COURSE_READ: 'course:read',
  COURSE_WRITE: 'course:write',
  COURSE_DELETE: 'course:delete',
  QUIZ_READ: 'quiz:read',
  QUIZ_WRITE: 'quiz:write',
  QUIZ_DELETE: 'quiz:delete',
  REVIEW_READ: 'review:read',
  REVIEW_APPROVE: 'review:approve',
  DASHBOARD: 'dashboard:read',
  AI_CHAT: 'ai:chat',
  CUSTOMER_READ: 'customer:read',
  CUSTOMER_REPLY: 'customer:reply',
  DOCUMENT_READ: 'document:read',
  DOCUMENT_WRITE: 'document:write',
  DOCUMENT_DELETE: 'document:delete',
  DOCUMENT_IMPORT: 'document:import',
  DOCUMENT_EXPORT: 'document:export',
  KNOWLEDGE_READ: 'knowledge:read',
  KNOWLEDGE_MANAGE: 'knowledge:manage',
  SETTINGS_MANAGE: 'settings:manage',
  AI_MODEL_READ: 'ai_model:read',
  AI_MODEL_MANAGE: 'ai_model:manage'
}
